[package]
name = "creusot-contracts-proc"
version = "0.1.0"
authors = ["Xavier Denis <xldenis@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "*"
uuid = { version = "*", features = ["v4"] }
pearlite-syn = { version = "*", path = "../pearlite-syn", features = ["full"] }
syn = "*"
proc-macro2 = { version = "1.0.36" }
